import React  from "react"

export function PrivacyPage(){
    return(
    <div className="privacy-container">
        <div className="privacy-main">
<h1>Privacy Policy</h1>
<h4>Last update: November 2024</h4>
<p>Gigster and its affiliated companies are committed to protecting the personal information of its users. Please read this Privacy Policy (this “Policy”) carefully to understand how Gigster International Ltd., 8 Kaplan St., Tel Aviv, Israel (“Gigster”, “we”) processes personnal information. This Policy describes how Gigster processes personal information of its users and other visitors browsing the Site (“users”) in connection with the Site and other services provided by Gigster as well as privacy practices that apply to affiliates, influencers and other collaborators.</p>
<p>By accessing or using www.Gigster.com, the Gigster mobile app, or any other related sites, applications, services and goods, or any other website operated by Gigster that links to this policy (each, the “Site”), as well as by registering to a Gigster account or to our affiliate, influencer or similar program, you acknowledge that you have read and understood this Policy. This Policy may change from time to time; any changes we make to this Policy will be posted on this Site, we will also take any other steps, to the extent required by applicable law, including notifying you about material changes. Changes to this Policy are effective as of the stated "Last Updated" date. We recommend that you check the Policy periodically for any updates or changes.</p>
<h2>1. The short version</h2>
<p>Information We Collect – You directly provide us with most of the information we collect: when you register to the Site, use it, complete forms, or register to any of our programs. We also collect information about your communications with Gigster as well as any of your posts on our blogs or forums and your communication with other users of Gigster. In addition, we automatically collect information while you access, browse, view or otherwise use the Site and receive information from third party vendors or other available sources.</p>
<p>Our Legal Basis for Using Your Personal Information - Where relevant under applicable laws, all processing of your personal information will be justified by a "lawful ground" for processing as detailed below.</p>
<p>How Do We Use the Information Collected? – We use personal information to provide you with quality service and security, to operate the Site, to perform our obligations to you and to develop, improve and personalize our service; to ensure marketplace integrity and security; to prevent fraud; to contact you and send you direct marketing communications; to promote and advertise the Site, our services and the Gigster marketplace; to comply with lawful requests by public authorities and to comply with applicable laws and regulations.</p>
<p>How Long Do We Keep Personal Information – We will keep personal information only for as long as is required to perform the purpose for which it was collected. However, in some cases we will retain personal information for longer periods of time.</p>
<p>Children - This Site is offered and available to users who are at least 18 years of age and of legal age to form a binding contract. Minors under 18 and at least 13 years of age, are only permitted to use the Site through an account owned by a parent or legal guardian with their appropriate permission. Minors under 13 are not permitted to use the Site or the Gigster services. We do not knowingly collect personal information from children under 13.</p>
<p>Sharing Personal Information with Third Parties – We share personal information with third parties in order to operate the Site, provide our services to you, perform obligations imposed on us by applicable laws and regulations, and prevent fraud, infringements and illegal activities.</p>

<p>Where We Process Personal Information – Some of the personal information you provide to us will be stored or processed on our behalf by third party suppliers and data processors and may be located in other jurisdictions, such as the United States and Israel.</p>

<p>Cookies – We use cookies and similar technologies (such as web beacons, pixels, tags, and scripts) to improve and personalize your experience, provide our services, analyze website performance and for marketing purposes.</p>

<p>Do Not Track (DNT) – Our Site does not respond to Do Not Track (DNT) signals.</p>

<p>External Links – The Site contains links to third party sites and if you link to a third party site from the Site, any data you provide to that site and any use of that data by the third party are not under the control of Gigster and are not subject to this Policy.</p>

<p>Security – We implement technical and organizational measures to maintain the security of the Site and your personal information and in preventing unauthorized access, loss, misuse, alteration, destruction or damage to it through industry standard technologies and internal procedures.</p>

<p>Specific Provisions for EU, EEA and UK Users – If you are an EU, EEA or UK user, you are entitled to receive further information on our processing and your rights as a data subject, as detailed below.</p>

<p>Specific Provisions for US Residents – If you are a US resident, depending on where you live, and subject to certain exceptions, you are entitled to specific privacy rights as detailed below.</p>

<p>Updating Personal Information – We take steps to ensure that the personal information we collect is accurate and up to date, and we provide you with the opportunity to update your information through your account profile settings. In the event that you believe your information is in any way incorrect or inaccurate, please let us know immediately.</p>

<p>Contact Us – You can exercise your rights over your personal information, by opening a Customer Relations ticket or contacting us at privacy@Gigster.com. For Gigster Workspace users, please contact us at workspace-support@Gigster.com. More details about the rights applicable to you are in the long version of the Policy.</p>

<p>The above are just the highlights. We encourage you to read more about the information we collect, how we use it, understand the meaning of cookies (no, you can’t eat it) and more in the detailed version of our Policy below.</p>


<h2>2. Information We Collect</h2>
<p>Information You Provide. When you register to the Site, use it, complete forms, participate in skills tests or surveys, sign up for events or newsletters, use the Site as collaborator, and/or register to our affiliate or influencer or similar program, we ask you to provide or otherwise collect personal information provided by you, including a valid email address, login details, name and username, profile details (including picture, education, profession and expertise), physical address or billing information, telephone number or other contact details, date of birth, transactional information, payment information (for example, your payment method and credit card number), taxpayer information and forms (including W-9 Forms and DAC-7 Forms), details about other social networks linked accounts, details about your listed gigs, orders, purchases and transactions rating and reviews, information included in user generated content and files uploaded by you to the Site. We may also collect identification information (such as copies of your government issued ID, passport, or driving license) and biometric information derived from photos and identification documents you submit for verification, as further detailed in our Help Center at “Verifying Your Identity”). Business sellers on Gigster are also requested to provide additional information to verify their business (learn more on "Account Verification"). We also collect and process information about or contained in your communications with Gigster as well as any of your posts on our blogs or forums and your communication with other users of Gigster.</p>

<p>Information We Collect Automatically. We collect information while you access, browse, view or otherwise use the Site including information about transactions and communications with other users, your searches, the pages you visited, browsed and scrolled as well as your clicks and other actions on the Site. We also, collect, use and process the information relating to such usage, including geo-location information, IP address, device and connection information, operating system, session duration, language, currency and keyboard setting, browser information and web-log information, and the URLs of the web pages you’ve viewed or engaged with before or after using the Site. We also collect and process information relating to the use of cookies and similar technologies, as detailed below.</p>

<p>Additionally, in order to improve your online experience at Gigster, we have implemented impression reporting. While you view our ads, we gather user Global Unique Identifier, HTTP request data like, user agent, IP, host, URL, country/continent from which request made, browser info, device/operating system/operating system version.</p>

<p>Information We Receive from Third Parties. We receive information from third party vendors and/or other commercially and/or publicly available sources, such as:</p>
<ul>
  <li>Third party vendors who provide us data to supplement the information we collect about you, in accordance with applicable laws. For example, we receive fraud and security warnings from service providers for our fraud prevention and risk assessment efforts. We also receive information about you, such as information about your organization and job title, from enrichment service providers to enhance and personalize your experience and offer you services that may be of interest for you as well as from advertising and marketing partners in order to manage and measure our campaigns.</li>
  <li>If you link, connect, or login to your account with a third-party service (e.g. Google, Facebook, LinkedIn), we receive certain information, such as your registration and profile information from that service. This information includes, for example, your email address, name and profile picture, but may vary and is controlled by that service or as authorized by you via your privacy settings at that service.</li>
  <li>If any other third party submits a report and/or complaint about you or your activity on Gigster, we may receive information relating to the specific report and/or complaint, review and address it.</li>
  <li>If you choose to invite contacts from your Google Workspace directory, we will have the ability to view details of contacts, subject to your Google Workspace permission. We will use this data to allow you to invite your contacts to your Gigster account. We will also use aggregated anonymised information for our internal purposes.</li>
  <li>If you integrate into your account information from third parties or otherwise integrate your account with third party systems, tools or products, we will receive certain information about you according to your permissions at such third parties.</li>
  <li>We also receive certain information about you, if you are invited to Gigster by another user (for example, as part of our collaboration tools and referral program), in such case we will receive limited information, such as your email address or other contact information, and we will use it for the same purpose it was provided and in accordance with this Policy.</li>
</ul>
<p>We combine your personal information with information we collect automatically or obtain from other companies and use it for the purposes detailed in this Policy.</p>

<h2>3. Our Legal Basis for Using Your Personal Information</h2>
<p>Where relevant under applicable laws, all processing of your personal information will be justified by a "lawful ground" for processing. In the majority of cases, processing will be justified on the legal basis that:</p>
<ul>
  <li>You have provided your consent for us to use your personal information for a specific purpose.</li>
  <li>Our use of your personal information is necessary to perform a contract or take steps to enter into a contract with you (e.g. to provide you with services which you have purchased).</li>
  <li>The processing is necessary to comply with a relevant legal obligation or regulatory obligation that we have (e.g. fraud prevention).</li>
  <li>The processing is necessary to support our legitimate interests as a business (e.g. to improve our services to you), subject to your overriding interests and fundamental rights and provided it is conducted at all times in a way that is proportionate.</li>
</ul>

<h2>4. How Do We Use The Information Collected?</h2>
<p>We will use your personal information for the following purposes:</p>
<ul>
  <li>To provide you with quality service and security, to operate the Site, to fulfill our obligations to you, and to develop, improve, and personalize our service. For example, we use personal information to verify your identity. We also use this information to establish and set up your account, verify or re-issue a password, log your activity, enable your communications with other members, provide customer support, and contact you from time to time. The information helps us to develop and improve our services, to understand and analyze our performance as well as your preferences and performance, and to customize and personalize our service and enhance your experience (including by making Gig suggestions, ranking search results, etc.).</li>
  <li>To ensure marketplace integrity, prevent fraud, and maintain a safe and secure marketplace and services. For example, we use personal information to monitor, track, and prevent illegal, fraudulent, and inappropriate activities, monitor content integrity, conduct security investigations and risk assessments, verify or authenticate information provided by you, investigate reports and complaints about users, enforce our Terms of Service, and comply with applicable laws. We conduct certain behavioral analytics to achieve the above objectives, and in limited cases, if we detect activity that we think poses a risk to the Gigster marketplace, other users, our community, or third parties, automated processes may restrict or limit your ability to use Gigster. If you would like to challenge any such decision, please contact us at privacy@Gigster.com.</li>
  <li>To contact you, as requested by you or as otherwise approved by you or permitted according to this Policy.</li>
  <li>To promote and advertise the Site, our services, and the Gigster marketplace. For example, we use the information collected from you for the purpose of sending direct marketing messages (as detailed below), to show you information that may be of interest to you, to organize and facilitate referral programs, contests, or other promotional activities or events.</li>
  <li>To maintain appropriate business records, to comply with lawful requests by public authorities, and to comply with applicable laws and regulations.</li>
</ul>
<p>We will ask for your consent before using information for a purpose other than those set out in this Policy.</p>
<p>Direct marketing:</p>
<ul>
  <li>We use your personal information to send you direct marketing communications about our products, services, or promotions from Gigster that may be of interest to you or our related services. This may be via email, post, SMS, telephone, or targeted online advertisements.</li>
  <li>Our processing of your personal information for marketing purposes is based on our legitimate interest, your consent, or other legal basis permitted by applicable laws. You have a right to prevent direct marketing of any form at any time - this can be exercised by following the opt-out link attached to each communication or by sending an email to optout@Gigster.com.</li>
  <li>We take steps to limit direct marketing to a reasonable and proportionate level and to send you communications which we believe may be of interest or relevance to you, based on the information we have about you.</li>
</ul>


<p>This Site is also protected by reCAPTCHA. Google Privacy Policy and Terms of Service apply with respect to data collected by reCAPTCHA. The use of Google reCAPTCHA is required in order to prevent fraud and misuse of the Site by use of automated machines. To learn more, please see Google's privacy policy.</p>

<h2>5. How Long Do We Keep Personal Information?</h2>
<p>We apply a general rule of keeping personal information only for as long as is required to perform the purpose for which it was collected. However, in some circumstances, we will retain your personal information for longer periods of time. We will retain personal information for the following purposes:</p>
        
      <h2>6. Children      </h2>  
        <p>This Site is offered and available to users who are at least 18 years of age or older and of legal age to form a binding contract. Minors under 18 and at least 13 years of age, are only permitted to use the Site through an account owned by a parent or legal guardian with their appropriate permission. Minors under 13 are not permitted to use the Site or the Gigster services. We do not knowingly collect personal information from children under 13. Parents and guardians should at all times supervise their children's activities. If we learn we have collected or received personal information from a child under 13, we will delete that personal information.</p>
        
        <h2>7. Sharing Personal Information with Third Parties        </h2>
        <p>We share your personal information with third parties as detailed below:</p>
        <ul>
  <li>With other users and Site visitors. Once you register, your username, country, and additional information regarding your activity is made public and is visible to all users of the Site. This information includes photos you upload, your published portfolio, Gig information, ratings and reviews, and additional information you may choose to add to your profile. We also offer you the opportunity to participate and post content publicly in forums, blogs and on other similar features. Please be aware that certain information, such as your user name and profile, together with the content uploaded by you, will be publicly displayed when you use such features. If you were verified as a business seller (trader) on Gigster, certain EU buyers may see some of the information as required by applicable laws (this includes you name, address, email, phone and business registration number, as well as your self-certification to comply with Gigster's policies and EU applicable rules). Your information will also be shared with other users when you message or otherwise communicate with them. When you publish your information and/or share your data with other Gigster users, you do so at your own risk. If you choose to share personal information with other users, including Sellers providing you a service via Gigster, such personal information is shared with other users as separate controllers. While our Terms of Service require Sellers to keep the information shared with them confidential, Gigster cannot ensure that all users will do so and it is your responsibility to ensure that other users will comply with your standards;</li>

  <li>With users with whom you interact. We share personal information to help facilitate interactions between users. For example, if you are a Buyer we may share certain information about you (such as the fact it is your first purchase on Gigster) with the Seller to ensure the services you receive from the Seller will fit your needs; such sharing of information is limited in scope, and is intended to improve the services provided by the Seller and your user experience;</li>

  <li>With Service Providers. We share personal information for business purposes with service providers that provide us with services for the purpose of operating the Site, opening and operating your account as well as providing ancillary services and solutions. These include, among others, hosting services, billing and payment processors and vendors, fraud detection and prevention services, CRM systems, forum hosting, community management services, data and cybersecurity services, web analytics and performance tools, translation tools, IT SaaS services, session recording, communication systems, mailing systems, data optimization and marketing services, data enrichment services, legal and financial advisors and technical consultants. Consistent with applicable legal requirements, we take appropriate technical and organizational measures to require third parties to adequately safeguard personal information and only process it in accordance with our instructions;</li>

  <li>When you submit a report or complaint about a user. We may share personal information about you when you submit reports or complaints about other users to allow them to protect their rights or as required by applicable laws.</li>

  <li>For legal reasons. We share personal information with law enforcement agencies, public authorities or other parties in order to respond to a subpoena or court order, judicial process or to regulatory authorities, if we believe we are required to do so by law, or that doing so is reasonably necessary to comply with legal processes; when we believe it necessary or appropriate to disclose personal information to law enforcement authorities, such as to investigate actual or suspected fraud or violations of law, breaches of security, or breaches of this Policy; to respond to claims against us; and to protect the rights, property, or personal safety of Gigster, our customers, or the public;</li>

  <li>For payments and fraud detection. We share personal information with payment processors, fraud detection agencies and similar third parties for the purpose of facilitating payments done via the Site, securing the Site and protecting it against fraud, unauthorized transactions (such as money laundering), claims or other liabilities;</li>

  <li>With social media partners. Our Site includes certain social media features, including single sign on features. We also share limited personal information with such social media platforms and marketing partners, such as Facebook and Google, to promote our services or the Gigster marketplace. Such features and third party services collect certain information about you and may set a cookie to enable their functionality. Such third parties’ features are governed by their policies;</li>

  <li>With our corporate affiliates. We share personal information with Gigster’s corporate affiliates for business and operational purposes, including for the purpose of operating our and our affiliates’ business, providing supplemental services to you, preventing fraud and maintaining safe and secure services, promoting our and our affiliates’ services and for other purposes listed herein;</li>

  <li>In the context of a corporate transaction. Personal information will also be disclosed if we go through a business transition such as a merger, sale, transfer of all or a portion of Gigster's assets, acquisition, bankruptcy or similar event. In the event that we sell any business or assets, we will disclose your data to the prospective buyer. If we or substantially all of our assets are acquired by a third party, information held by us about our users will be one of the transferred assets.</li>
</ul>

        <h2>8. Where We Process Your Personal Information        </h2>
        <p>Some of the personal information you provide to us will be stored or processed on our behalf by third party suppliers and data processors and may be located in other jurisdictions, such as the United States and Israel, whose laws may differ from the jurisdiction in which you live. Whether to third parties or internally, there are also transfers of personal information from the European Economic Area (“EEA”) to countries outside of the EEA not deemed to provide an adequate level of data protection from a European data protection perspective, such as the United States. With regard to data transfers to such recipients outside of the EEA we provide appropriate safeguards, in particular, by way of entering into European Union (EU) standard contractual clauses as amended from time to time, and/or equivalent data transfer safeguards. We will take all steps reasonably necessary to ensure that your personal information is treated securely and in accordance with this Policy.</p>
        <h2>9. Cookies</h2>
        <p>We use cookies and similar technologies (such as web beacons, pixels, tags, and scripts) to improve and personalize your experience, provide our services, analyze website performance and for marketing purposes. Where the use of cookies on our Site involves the processing of your personal information, this Policy applies. The types of cookies used by us and our partners in connection with the Site and our service can be classified into the categories “essential cookies”, “analytics cookies” and “marketing cookies”.</p>
        <h2>10. Do Not Track        </h2>
        <p>Do Not Track (DNT) is a privacy preference that users can set in some web browsers, allowing users to opt out of tracking by websites and online services. We do not honor browser requests not to be tracked online (known as “Do Not Track”), but our Cookie Policy describes how you can opt out of receiving cookies.</p>
        <h2>11. External Links        </h2>
<p>Please note that the Site contains links to third party sites and if you navigate to a third party site from the Site, any data you provide to that site and any use of that data by the third party are not under the control of Gigster and are not subject to this Policy. You should consult the privacy policies of each site you visit. This Policy applies solely to personal information collected by our Site. If you upload content, including personal information, to a social network and then tag the Site, your submission will be subject to that social network's terms of use and privacy policy, even where you post on an official Gigster page on the social network. We do not have control over these terms of use and privacy policies and have not reviewed their adequacy. You should therefore review these before submitting any personal information.</p>
<h2>12. Security</h2>
<p>We implement technical and organizational measures in order to maintain the security of the Site, our services and personal information and in preventing unauthorized access, loss, misuse, alteration, destruction or damage to it through industry standard technologies and internal procedures. Among other things, we regularly maintain a PCI DSS (Payment Card Industry Data Security Standards) certification (with respect to payment by credit cards), as required. In addition, we contractually ensure that any third party processing your personal information equally provides for confidentiality and integrity of your data in a secure way. However, the transmission of data via the internet is not completely secure, and although we will do our best to protect your personal information, we cannot guarantee the security of your data transmitted to the Site. Once we have received your data, we will use strict procedures and security features to try to prevent unauthorized access.</p>
<p>Users who have registered to the Site agree to keep their password in strict confidence and not disclose such password to any third party.</p>
<p>Further information about our data security practices can be provided on request.
</p>





        </div>
        </div>
    )}